# Load Numpy

In [1]:
import numpy as np

# BASICS

In [2]:
# 1 diemnsional array
a= np.array([2,5,9])
print(a)

[2 5 9]


In [3]:
# 2 dimensional array
b= np.array([[5,8,9],[8,7,9]])
print(b)

[[5 8 9]
 [8 7 9]]


In [4]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Shape (Like number of row and column)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get type, like int32, float etc
print(a.dtype)
print(b.dtype)

int32
int32


In [8]:
# Wecan change dtype in array like this
a=np.array([2,5,9], dtype='int16')

In [9]:
# int16 take less space than int32

In [10]:
# Get storage size of item in array
print(a.itemsize)
print(b.itemsize)

2
4


In [11]:
# Get total size (Method 1)
print(a.size* a.itemsize)

6


In [12]:
# Get total size (Method 2)
print(a.nbytes)

6


# Accessing/ Changing Specific elements,row, columns etc

In [13]:
a= np.array([[1,2,3,4,5,6,7],[2,5,6,9,8,7,4]])
print(a)

[[1 2 3 4 5 6 7]
 [2 5 6 9 8 7 4]]


In [15]:
# Get specific element [row, column]
a[1,5] #2nd row, 6th column

7

In [17]:
# Get specific row (in column we write :)
# Getting first row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get specific column (in row we write :)
# Getting third column
a[:,2]

array([3, 6])

In [19]:
# More fancy slection [startindex:endindex:stepsize]
# we select first row and slect 2nd column to second last column with a step size of 2
a[0,1:-2:2]

array([2, 4])

In [20]:
# More fancy slection [startindex:endindex:stepsize]
# we select first row and slect 2nd column to last column with a step size of 2
a[0,1:-1:2]

array([2, 4, 6])

In [21]:
# Change the element
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 2  5  6  9  8 20  4]]


In [22]:
# change two value in 2 dimensional
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 2  5  2  9  8 20  4]]


In [23]:
# 3D Example

In [24]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get Specific element (which space, row, column) here i want to select 4 from first space
b[0,1,1]

4

In [26]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [27]:
# Replace
b[:,1,:]= [[8,8],[7,5]]

In [28]:
b

array([[[1, 2],
        [8, 8]],

       [[5, 6],
        [7, 5]]])

# Different type of Arrays

In [29]:
# All Os matrix
# One Dimensional
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
# Two Dimensional
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
# Three Dimensional
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
# All 1s matrix (4 dimensinal with dtype int32)
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [33]:
# Any Other Number (like we want 2x2 matrix with fill all element with 90)
np.full((2,2),90)

array([[90, 90],
       [90, 90]])

In [34]:
# Any Other Number (like we want 2x2 matrix with fill all element with 90 and dtype float)
np.full((2,2),90, dtype='float32')

array([[90., 90.],
       [90., 90.]], dtype=float32)

In [35]:
# Any other number (full like) we want a like array with elements of 4 everywhere
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random Decimal Numbers (Two Dimensional)
np.random.rand(2,3)

array([[0.35288834, 0.34742994, 0.00908144],
       [0.86542748, 0.7069307 , 0.4103902 ]])

In [38]:
# Random Decimal Numbers (Three Dimensional)
np.random.rand(3,2,3)

array([[[0.8468735 , 0.43227145, 0.6575373 ],
        [0.6139668 , 0.74917098, 0.42257349]],

       [[0.22339992, 0.86248373, 0.58667845],
        [0.9535568 , 0.11924299, 0.5143403 ]],

       [[0.34437779, 0.74691857, 0.76145431],
        [0.10909217, 0.2690523 , 0.23353535]]])

In [39]:
# If we want a random numbers array like 'a' array
np.random.random_sample(a.shape)

array([[0.21917742, 0.95339951, 0.69910727, 0.11014384, 0.79439659,
        0.61473302, 0.26312836],
       [0.59417687, 0.24465437, 0.96121695, 0.98499782, 0.49499253,
        0.87642085, 0.01549983]])

In [40]:
# Random Integar Numbers
# Want an random integat array from 4 to 7 and shape (3,3)
np.random.randint(4,8, size=(3,3))

array([[7, 5, 4],
       [6, 6, 5],
       [5, 6, 5]])

In [41]:
# The Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
#Repeat an array
arr= np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [43]:
#Repeat an array (Two Dimensional)
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
#Repeat an array (Two Dimensional)
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


# Exercise

In [46]:
output= np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
z=np.zeros((3,3))

In [48]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [51]:
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
#Be careful whwn copy array

In [56]:
# From this code a=b and when we change element of b, element of a will also change
a1= np.array([1,2,3])
b1=a1
b1[0]=200
print(a1)
print(b1)

[200   2   3]
[200   2   3]


In [57]:
# From this code, when we change element of b, elemnt of a will not change
a1= np.array([1,2,3])
b1=a1.copy()
b1[0]=200
print(a1)
print(b1)

[1 2 3]
[200   2   3]


# Basic Mathematics

In [58]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [59]:
a+2

array([3, 4, 5, 6])

In [60]:
a-2

array([-1,  0,  1,  2])

In [61]:
a*2

array([2, 4, 6, 8])

In [62]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [63]:
b=np.array([2,5,6,4])
a+b

array([3, 7, 9, 8])

In [64]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [65]:
#Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [66]:
np.cos(b)

array([-0.41614684,  0.28366219,  0.96017029, -0.65364362])

# LINEAR ALGEBRA

In [68]:
#Mutiplication
a2= np.ones((2,3))
print(a2)
b2=np.full((3,2),2)
print(b2)
np.matmul(a2,b2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [69]:
#Determinant
c= np.identity(3)
np.linalg.det(c)

1.0

# STATISTICS

In [70]:
stats= np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
#Minimum from all element of array
np.min(stats)

1

In [72]:
#Minimum from row element of array
np.min(stats, axis=0)

array([1, 2, 3])

In [73]:
#Maximum from all element of array
np.max(stats)

6

In [74]:
#Maximum from row
np.max(stats,axis=0)

array([4, 5, 6])

In [75]:
#Sum of all elements
np.sum(stats)

21

In [76]:
#Sum column wise
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [77]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [79]:
# Vertically stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
# Vertically stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [81]:
#Horizontal stack
h1= np.ones((2,4))
h2= np.ones((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Load Data from file

In [82]:
filedata= np.genfromtxt('data.txt',delimiter=',')
filedata= filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [83]:
#Bolean masing and advanced indexing
# It shows true and false value
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [84]:
# It will show actual value
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [86]:
# You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [87]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [88]:
((filedata>50) &(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [89]:
(~((filedata>50) &(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])